version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo install a required package
      - npm install react-scripts
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build (maybe zip build dir) completed on `date`
artifacts:
  nodejs_aartifacts:
    base-directory: .
    files:
      - build/
